### ISSUE TITLE
El enlace incluye la coma

### ISSUE THREAD

**Issue by jeremyjsx** [GarajedeIdeas/garajedeideas#1]
En el header del readme de Garaje de Ideas, el enlace a su sitio web está bien, sin embargo; la coma está incluida dentro del enlace y me parece que lo correcto sería que la coma no sea parte del enlace
![image](https://github.com/GarajedeIdeas/garajedeideas/assets/115596285/a4181a5d-8f17-4430-a284-7fc764e351d1)

**Comment by GarajedeIdeas** [comment]
Arreglado ✓. ¡Gracias!
